[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.31.1"
tungstenite = "0.17.3"
prost = "0.10"

[build-dependencies]
prost-build = "0.10"